version: '3'
services:
  postgres:
    build:
      context: ./docker/postgresql/
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=horse_api
    volumes:
      - pgsql-data:/var/lib/postgresql/data/pgdata
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver --host 0.0.0.0 --debug --reload
    volumes:
      - .:/usr/src/horse_api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
volumes:
  pgsql-data:
