version: '3'
services:
  postgres:
    image: postgres:9.5.4
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=horse_api
    volumes:
      - pgsql-data:/var/lib/postgresql/data/pgdata
  web:
    build:
      context: ./docker/nginx/
    ports:
      - "8080:80"
    depends_on:
      - postgres
      - app
  app:
    build:
      context: .
volumes:
  pgsql-data:
